config/routes.rb
JqueryTemplateBlog::Application.routes.draw do
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  respond_to :html, :js, :json

  def index
    respond_with(@blogs = Blog.all)
  end

  def new
    respond_with(@blog = Blog.new)
  end

  def edit
    respond_with(@blog = Blog.find(params[:id]))
  end

  def show
    # redirect_to blogs_url
    respond_with(@blog = Blog.find(params[:id]))
  end

  def create
    @blog = Blog.new(params[:blog])

    if @blog.save
      respond_with @blog do |format|
        format.html {redirect_to blogs_url, notice: 'You have successfully added your blog.'}
        format.js
      end
    else
      respond_with @blog do |format|
        format.html {render action: "new"}
        format.js {render 'new.js.erb'}
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update_attributes(params[:blog])
      respond_with @blog do |format|
        format.html {redirect_to blogs_url, notice: 'You have successfully updated your blog.'}
        format.js
      end
    else
      respond_with @blog do |format|
        format.html {render action: "edit"}
        format.js {render 'new.js.erb'}
      end
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_url, :notice => 'You have successfully removed your blog.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for(@blog) do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2
        = pluralize(@blog.errors.count, "error")
        prohibited this blog from being saved:
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description

  .actions
    = f.submit "Save"

app/views/blogs/edit.html.haml
%h1 Editing blog
= render 'form'
= link_to 'Show', @blog
|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing Blogs
%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th
  - @blogs.each do |blog|
    %tr
      %td= blog.title
      %td= blog.description
      %td= link_to 'Show', blog
      %td= link_to 'Edit', edit_blog_path(blog)
      %td= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete

%div
= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog
= render 'form'
= link_to 'Cancel', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @blog.title
%p
  %b Description:
  = @blog.description

= link_to 'Edit', edit_blog_path(@blog)
or
= link_to 'Back', blogs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryTemplateBlog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>